### PR TITLE
add Composer.deserialize and add support for INSECURE_SSL in wskprops

### PR DESCRIPTION
**Pull request by starpit**
1) Composer.deserialize
2) test for deserialize
3) support INSECURE_SSL in wskprops
4) make initialization of this.wsk optional

tests run to success locally

### CODE REVIEW

**Comment by tardieu** [comment]
why do you need to make initialization of this.wsk optional?

**Comment by starpit** [comment]
for a couple of reasons.

1) ~/.wskprops might not exist when the shell is compiling the plugin registry
2) during a shell session, the .wskprops file may change, but Composer loads it only once

**Comment by starpit** [comment]
oh, and it's a bit slow, and the shell has already done this init

**Comment by tardieu** [comment]
ok then I think it should be lazily initialized

**Comment by tardieu** [comment]
merging this as is... will improve later

**Pull request merged**
